### ISSUE TITLE
OAuth 2.0 tokens: New web services endpoints to request access and refresh token

### ISSUE THREAD

**Issue by laufhannes** [waytohealth/oauth2-withings#14]
I just quote this part from Withings' changelog:

> [06/07/2020]
> ...
> OAuth 2.0 tokens: New web services endpoints to request access and refresh token. Add a signature mechanism scheme to not transmit the client secret. To get more information, please refer to [OAuth 2.0 services](https://developer.withings.com/oauth2/#tag/oauth2) section.

I guess the `getBaseAccessTokenUrl` method should return `https://wbsapi.withings.net/v2/oauth2` instead?
```diff
    public function getBaseAccessTokenUrl(array $params)
    {
-        return static::BASE_WITHINGS_URL.'/oauth2/token';
+        return static::BASE_WITHINGS_API_URL.'/v2/oauth2';
    }
```

**Comment by acleitner** [comment]
Thank you for pointing this out. I've added this change to our internal backlog, meanwhile the existing access token URL is still active. We're also open to Pull Requests if you'd like to make this update yourself.

**Comment by mipapo** [comment]
@acleitner  Just FYI - Old endpoints for tokens will be disabled in september (https://support.withings.com/hc/en-us/articles/360016745358--BREAKING-Deprecating-access-and-refresh-tokens-endpoints)

**Comment by acleitner** [comment]
@mipapo thanks for flagging this. I have updated the existing ticket I created back in November with this additional info and increased its priority.

**Comment by mipapo** [comment]
Thanks  - Issue can be closed
