### ISSUE TITLE
Authentication Code - Service unavailable since 4 march on Withings

### ISSUE THREAD

**Issue by harkor** [waytohealth/oauth2-withings#7]
Hello,

I tried to get my authentication code since Wednesday but without success.

![image](https://user-images.githubusercontent.com/1044182/76141377-d92f3580-6063-11ea-866b-8ded49852521.png)

It's possible to check on your side if it's a real problem on withings server ?

Thanks

**Comment by mkopinsky** [comment]
This library isn't maintained by Withings. We are consumers of the API just like you. I'd recommend reaching out to Withings support directly.

**Comment by harkor** [comment]
I know, I'm just asking if you could just make a test on your side to check if the problem it's not my app settings...
